apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: servicemonitor-app
  labels:
    team: frontend
  namespace: cattle-monitoring-system
spec:
  namespaceSelector:
    matchNames: 
    - cattle-monitoring-system
  selector:
    matchLabels:
      app: servicemonitor-app
  endpoints:
  - port: web
