apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicemonitor-app
  namespace: cattle-monitoring-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: servicemonitor-app
  template:
    metadata:
      labels:
        app: servicemonitor-app
    spec:
      containers:
      - name: servicemonitor-app
        image: fabxc/instrumented_app
        ports:
        - name: web
          containerPort: 8080